apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: registered-guanaco-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: registered-guanaco-go 
  name: registered-guanaco-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: registered-guanaco-go 
